feat: article Kapsule and cert-manager
particuleio/website pull request #38
Opened 2020-11-24 16:11 UTC by rguichard

2020-11-26 08:59 UTC, ArchiFleKs requested changes

2020-11-26 08:59 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +Cert-Manager est un gestionnaire natif de certificats pour Kubernetes. Il
add link

2020-11-26 08:59 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +moins que votre fournisseur bloque le port 80, mais qui fait ça ?). DNS-01
mettre des certificat ACME dans des archi interne maybe

2020-11-26 08:59 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +mécanisme à l'ensmeble du cluster, nous allons utiliser un `ClusterIssuer`. Il
ensemble

2020-11-26 08:59 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +Question de simplicité, on va faire la première solution ^^
"Nous allons partir sur"

2020-11-26 08:59 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +Vous pouvez reprendre [notre précédent article]() sur le sujet.
missing link

2020-11-26 08:59 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +Ou alors, vous pouvez le module Terraform écrit par Particule vous
pouvez utiliser

2020-11-26 14:07 UTC, rguichard commented on content/blog/scaleway-cert-manager.fr.md
> +moins que votre fournisseur bloque le port 80, mais qui fait ça ?). DNS-01
pas compris

2020-11-26 14:09 UTC, ArchiFleKs commented on content/blog/scaleway-cert-manager.fr.md
> +moins que votre fournisseur bloque le port 80, mais qui fait ça ?). DNS-01
Un des use case de DNS01 serait d'avoir des certificats valide acme pour une utilisation interne non publiée vers l'exterieur

2020-11-26 14:13 UTC, rguichard commented on content/blog/scaleway-cert-manager.fr.md
> +moins que votre fournisseur bloque le port 80, mais qui fait ça ?). DNS-01
OK mais c'est quoi le rapport avec le texte que tu commentes ?

2020-11-30 07:11 UTC, rguichard commented
Can we merge?

2020-11-30 07:45 UTC, ArchiFleKs approved these changes

2020-11-30 07:45 UTC, merged