feat: article k8s local
particuleio/website pull request #45
Opened 2021-01-12 10:23 UTC by rguichard

Must be merged after https://github.com/particuleio/navigator-hugo/pull/13

2021-01-12 13:28 UTC, tbobm reviewed
I've noticed a couple of minor typos / wording issues

2021-01-12 13:28 UTC, tbobm commented on content/blog/kubernetes-local.fr.md
> +matérielles ou virtuelle relativement complexes. Le cluster etcd peut être
An `s` seems to be missing in `virtuelle`

2021-01-12 13:28 UTC, tbobm commented on content/blog/kubernetes-local.fr.md
> +configurations sont possibles et chacune à ses avantages et ses inconvénients.
Minor typo in `chacune a ses`

2021-01-12 13:28 UTC, tbobm commented on content/blog/kubernetes-local.fr.md
> +Storage Class, etc) ne seront peut être pas disponibles.
Minor typo in `peut-être` (missing `-`)

2021-01-12 13:28 UTC, tbobm commented on content/blog/kubernetes-local.fr.md
> +présupposeque plusieurs choses soient installées, en amont ou en aval :
Minor typo in `présupposeque` (missing whitespace between `présuppose` and `que`)

2021-01-12 13:28 UTC, tbobm commented on content/blog/kubernetes-local.fr.md
> +Est inclu :
Maybe replace `Est inclu` with `Sont inclus` ?

2021-01-12 13:28 UTC, tbobm commented on content/blog/kubernetes-local.fr.md
> +D'autres solutions existent évidemment, nous n'avons choisi de ne pas les
Maybe remove the `n'` from `nous [n']avons choisi` ?

2021-01-12 17:11 UTC, rguichard commented
Fixes apply.

2021-01-13 08:47 UTC, ArchiFleKs requested changes

2021-01-13 08:47 UTC, ArchiFleKs commented on content/blog/kubernetes-local.fr.md
> +Malgré le fait que [Docker est désormais deprecated par
Weird phrasing, remove "Malgré le fait que"

2021-01-13 11:27 UTC, ArchiFleKs approved these changes

2021-01-13 11:30 UTC, merged