feat: add thanos article
particuleio/website pull request #48
Opened 2021-01-26 17:28 UTC by ArchiFleKs

2021-02-23 18:57 UTC, tbobm requested changes
Really nice article! :ok_hand:

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +Prometheus stores metrics on disk, you have to make a choices between storage
`choice`

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +takes longer than the scrape interval this is going to cause issue.
What do you think of: `At scale, if the scrape duration of all your prometheus targets takes longer than the scrape interval, you might encounter some severe issues.` ?

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +"pushing metrics" part in this article, you can read about the pros and cons of
`article, you` -> `article. You` (?)

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +[Thanos](https://thanos.io/) is a "*Open source, highly available Prometheus
`a` -> `an` ?

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +Additionnals Thanos components deployed:
`Additionnals` -> `Additionnal` (?)

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +metrics stored inside an object store. Downsampling is the fact of loosing
`the fact` -> `the action` ?

2021-02-23 18:57 UTC, tbobm commented on content/blog/thanos-monitoring.en.md
> +granularity on your metrics over time: for example you may want to keep your
`time: for example you may`

maybe one of:
- `time. You may`
- `time. For example you may`

2021-02-24 11:53 UTC, rguichard reviewed
Very good ! I missed a lot of prometheus/Prometheus - thanos/Thanos. I think we should use an uppercase first letter everywhere.

There are two PNG bigger than 1MB. Can you make them smaller ?

I'll make the OG image

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +Title: Multi Cluster Monitoring with Thanos
clusters ?

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +Summary: Monitor multiple Kubernetes Cluster with Prometheus and Thanos
Clusters ?

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +[Thanos store](https://thanos.io/tip/components/store.md/) acts a gateway to
acts as*

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +There are multiple way to deploy these component into multiples Kubernetes
components

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +There are multiple way to deploy these component into multiples Kubernetes
multiple

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +  * All thanos component are deployed
components

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +  * Query Frontend which serve as a datasource endpoints for Grafana
endpoint

2021-02-24 11:53 UTC, rguichard commented on content/blog/thanos-monitoring.en.md
> +Observee cluster are Kubernetes cluster with minimal prometheus/thanos
clusters

2021-02-24 14:59 UTC, rguichard approved these changes
lgtm

2021-02-24 15:00 UTC, merged